repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
        exclude: ^(packaging/.*|mkdocs\.yml)$
        args:
          - --allow-multiple-documents
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--config=setup.cfg]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: yapf
        language: python
        types: [python]
        exclude: ^(build/|site/|csrc/third_party/|src/cache_dit\.egg-info/)
        additional_dependencies:
          - yapf==0.40.2
        args:
          - --in-place
          - --parallel

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        exclude: ^(build/|site/|csrc/third_party/|src/cache_dit\.egg-info/)
        args:
          - --in-place
          - --tab-width=2
          - --wrap-summaries=100
          - --wrap-descriptions=100
